Garage3/Controllers/MembersController.cs
using AutoMapper;
using Garage3.Data;
using Garage3.Models.Entities;
using Garage3.Models.ViewModels.Members;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Garage3.Controllers
{
    public class MembersController : Controller
    {

        private readonly IMapper _mapper;
        private readonly Garage3Context _context;

        public MembersController(Garage3Context context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(string PersonalNo, string FirstName, string LastName)
        {
            var member = _context.Member
                       .Where(member => (string.IsNullOrWhiteSpace(PersonalNo) || member.PersonalNo.Contains(PersonalNo)) &&
                      (string.IsNullOrWhiteSpace(FirstName) || member.FirstName.StartsWith(FirstName)) &&
                      (string.IsNullOrWhiteSpace(LastName) || member.LastName.StartsWith(LastName)));

            var model = _mapper.ProjectTo<MembersVehiclesViewModel>(member);
            if (model == null)
            {
                return NotFound();
            }
            var sortModel = await model.ToListAsync();

            return View(sortModel.OrderBy(m => m.FirstName.Substring(0, 2), StringComparer.Ordinal));
        }

        // GET: Members/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var member = await _mapper.ProjectTo<MembersVehiclesViewModel>(_context.Member)
                                       .FirstOrDefaultAsync(m => m.Id == id);
            if (member == null)
            {
                return NotFound();
            }
            return View(member);
        }

        // GET: Members/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PersonalNo,FirstName,LastName")] Member member)
        {
            if (ModelState.IsValid)
            {
                _context.Add(member);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        // GET: Members/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member.FindAsync(id);
            if (member == null)
            {
                return NotFound();
            }
            return View(member);
        }

        // POST: Members/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PersonalNo,FirstName,LastName")] Member member)
        {
            if (id != member.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(member);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MemberExists(member.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        // GET: Members/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member.FirstOrDefaultAsync(m => m.Id == id);
            
            if (member == null)
            {
                return NotFound();
            }
            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var member = await _context.Member.FindAsync(id);
            
            _context.Member.Remove(member);
            await _context.SaveChangesAsync();
            
            return RedirectToAction(nameof(Index));
        }

        private bool MemberExists(int id)
        {
            return _context.Member.Any(e => e.Id == id);
        }

        public IActionResult VerifyPersonalNo(string personalNo)
        {
            bool PersonalNoExists = _context.Member.Any(m => m.PersonalNo == personalNo);
            if (PersonalNoExists)
            {
                return Json($"A Member with personl number {personalNo} already exists.");
            }
            return Json(true);
        }

    }
}

Garage3/Controllers/VehiclesController.cs
using AutoMapper;
using Garage3.Data;
using Garage3.Models;
using Garage3.Models.Entities;
using Garage3.Models.ViewModels.Vehicles;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Garage3.Controllers
{
    public class VehiclesController : Controller
    {
        private readonly Garage3Context _context;
        private readonly IMapper _mapper;

        public VehiclesController(Garage3Context context, IMapper mapper)
        {
            _mapper = mapper;
            _context = context;
        }

        public async Task<IActionResult> Index(string RegNo, string drpVehicleType,string drpVehicleStatus)
        {
            var VehicleTypesList = _context.VehicleType
                                           .Select(e => new SelectListItem
                                           {
                                               Text = e.Type,
                                               Value = e.Type
                                           })
                                           .Distinct()
                                           .AsEnumerable();

            ViewBag.VehicleTypes = VehicleTypesList;

            var garage3Context = _context.Vehicle
                .Include(v => v.Member)
                .Include(v => v.VehicleType)
                .Where(v => (string.IsNullOrWhiteSpace(RegNo) || v.RegNo.Contains(RegNo)) &&
                (string.IsNullOrWhiteSpace(drpVehicleType) || v.VehicleType.Type.StartsWith(drpVehicleType)) &&
                (string.IsNullOrWhiteSpace(drpVehicleStatus) || v.IsCheckedOut == bool.Parse(drpVehicleStatus)))
                .OrderByDescending(v=>v.ArrivalTime);
            if (garage3Context == null)
            {
                return NotFound();
            }
            return View(await garage3Context.ToListAsync());
        }

        public IActionResult Home()
            {
            return View();
            }

        [HttpPost]
        public async Task<IActionResult> Home(string regNo)
        {
            TempData["UserMessage"] = "";
            if (await VehicleExistsByRegNo(regNo.ToUpper()) == false)
            {
                // If a vehicle doesn't exist, then we need to create a member or connect a member to this vehicle.
                TempData["UserMessage"] = $"The vehicle with license plate number {regNo.ToUpper()} isn't registrated and need to be registred.";
                return RedirectToAction(nameof(Registration));
            }
            else
            {
                // It's probably just checkedout atm and needs to checkin again.
                if(await _context.Vehicle.AnyAsync(v => v.RegNo == regNo && v.IsCheckedOut == false))
                {
                    TempData["UserMessage"] = $"The vehicle with license plate number {regNo.ToUpper()} is already parked in the garage. Please try again.";
                    return View();
            }
                TempData["UserMessage"] = $"The vehicle with license plate number {regNo.ToUpper()} is already registrated and only need to check in.";
                return RedirectToAction(nameof(CheckIn), new { id = regNo }) ;
        }
        }

        public IActionResult Registration()
        {
            ViewData["VehicleType"] = new SelectList(_context.VehicleType, "Id", "Type"); 

            ViewData["MemberId"] = new SelectList(_context.Member, "Id", "Id");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Registration(RegistrationViewModel vehicle)
        {
            if (ModelState.IsValid)
            {

                bool regNoExists = _context.Vehicle.Any(v => v.RegNo == vehicle.RegNo);
                if (!regNoExists)
                {
                    var member = _context.Member.FirstOrDefault(M => M.PersonalNo == vehicle.PersonalNo);
                    vehicle.MemberId = member.Id;
                    vehicle.RegNo = vehicle.RegNo.ToUpper();
                    vehicle.Color = vehicle.Color.Substring(0, 1).ToUpper() + vehicle.Color.Substring(1);
                    vehicle.Make = vehicle.Make.Substring(0, 1).ToUpper() + vehicle.Make.Substring(1);
                    vehicle.Model = vehicle.Model.Substring(0, 1).ToUpper() + vehicle.Model.Substring(1);
                    vehicle.ArrivalTime = System.DateTime.Now;
                    vehicle.IsCheckedOut = true;
                    var CurrentVehicle= _context.Add(_mapper.Map<Vehicle>(vehicle));
                    await _context.SaveChangesAsync();

                    //////Check In 
                    ParkingController parkingController = new ParkingController(_context);
                    await parkingController.ParkVehicle(CurrentVehicle.Entity.Id);

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("RegNo", "A vehicle with this register Number is already in the garage.");
                }
            }
            ViewData["MemberId"] = new SelectList(_context.Member, "Id", "Id", vehicle.MemberId);
            return View(vehicle);
        }
        public IActionResult VerifyPersonalNo(string personalNo)
        {
            bool PersonalNoNotExists = _context.Member.Any(m => m.PersonalNo == personalNo);
            if (!PersonalNoNotExists)
            {
                return Json($"A Member with personl number {personalNo} Not Has a membership.");
            }
            else
            { 
             var BirthDate = personalNo.Substring(0, 4) + "/" + personalNo.Substring(4, 2) + "/" + personalNo.Substring(6, 2);
            var DiffInterval = DateTime.Now.Subtract(DateTime.Parse(BirthDate)).Days;
            var Age = DiffInterval / 365;

            if (Age < 18)
            {
                return Json($"A Member with personl number {personalNo} less than 18 years Not allowed to chek in.");
            }
            }
            return Json(true);
        }

        // CHECKIN VIEW NEEDS TO BE COMPLETE!!!
        [Route("Vehicles/CheckIn/{regNo}")] // Route need to be definied to work with a string as param at this point.
        public async Task<IActionResult> CheckIn(string regNo)
        {
            if (regNo == null)
            {
                return NotFound();
            }

            var model = await _context.Vehicle
                                      .FirstOrDefaultAsync(v => v.RegNo == regNo);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        public async Task<IActionResult> CheckOut(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var vehicle = await _context.Vehicle.FindAsync(id);
            vehicle.IsCheckedOut = true;
             await _context.SaveChangesAsync();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vehicle);
                   
                    var parking = await _context.Parking.Where(v => v.VehicleId == vehicle.Id).ToListAsync();
                    for (int i = 0; i < parking.Count; i++)
                    { _context.Parking.Remove(parking[i]); } 
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleExists(vehicle.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Leave(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle
                .Include(v => v.Member)
                .Include(v => v.VehicleType)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (vehicle == null)
            {
                return NotFound();
            }

            var model = new LeaveViewModel
            {
                Id = vehicle.Id,
                RegNo = vehicle.RegNo,
                Type = vehicle.VehicleType.Type,
                Make = vehicle.Make,
                Model = vehicle.Model,
                ArrivalTime = vehicle.ArrivalTime,
                MemberFullName = $"{vehicle.Member.FirstName} {vehicle.Member.LastName}"
            };
            return View(model);
        }

        [HttpPost, ActionName("Leave")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LeaveConfirmed(int id)
        {
            var vehicle = await _context.Vehicle.FindAsync(id);

            _context.Vehicle.Remove(vehicle);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Receipt", vehicle); // Action, Controller, object
        }

        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle.FindAsync(id);
            if (vehicle == null)
            {
                return NotFound();
            }
             ViewData["VehicleType"] = new SelectList(_context.VehicleType, "Id", "Type");
            ViewData["MemberId"] = new SelectList(_context.Member, "Id", "Id", vehicle.MemberId);
            return View(vehicle);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

Garage3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Garage3</title>
    <!-- Styles -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-table/bootstrap-table.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand  text-light " asp-area="" asp-controller="Vehicles" asp-action="Home">
                    <img src="~/images/parking-icon-Header.png" height="36" />
                    Garage 3.0
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle"  id="navbarDropdownVehicle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Vehicles
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownVehicle">
                                <a class="dropdown-item" asp-controller="Vehicles" asp-action="Index">Vehicles</a>
                                <a class="dropdown-item" asp-controller="Vehicles" asp-action="Registration">Check In Vehicle</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle"  id="navbarDropdownMember" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Members
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMember">
                                <a class="dropdown-item" asp-controller="Members" asp-action="Index">Members</a>
                                <a class="dropdown-item" asp-controller="Members" asp-action="Create">Member Registration</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Admin
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="VehicleType" asp-action="Create">Create Vehicle Type</a>
                                <a class="dropdown-item" asp-controller="VehicleType" asp-action="Index">View Vehicle Type</a>
                                <div class="dropdown-divider"></div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-secondary">
        <div class="container">
            &copy; 2021 - G1 Group AB
        </div>
    </footer>
    <!-- JavaScripts -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap-table/bootstrap-table.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script> <!-- Custom JS -->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>